version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "ca-dir.patch",
]
SPDX-FileCopyrightText = "openssl-1.1 contributors"
SPDX-License-Identifier = "TODO-Choose-a-license"

[[annotations]]
path = [
    "CVE-2023-5678.patch",
    "CVE-2024-0727-1.patch",
    "CVE-2024-0727-2.patch",
    "CVE-2024-2511.patch",
    "CVE-2024-4741.patch",
    "CVE-2024-5535-1.patch",
    "CVE-2024-5535-2.patch",
    "CVE-2024-5535-3.patch",
    "CVE-2024-5535-4.patch",
    "CVE-2024-5535-5.patch",
    "CVE-2024-5535-6.patch",
    "CVE-2024-5535-7.patch",
    "CVE-2024-5535-8.patch",
    "CVE-2024-9143.patch",
    "CVE-2024-13176.patch",
    "CVE-2025-9230.patch",
]
SPDX-FileCopyrightText = "Debian contributors"
SPDX-License-Identifier = "TODO-Choose-a-license"

[[annotations]]
path = [
    "CVE-2025-69419-1.patch",
    "CVE-2025-69419-2.patch",
]
SPDX-FileCopyrightText = "RHEL contributors"
SPDX-License-Identifier = "TODO-Choose-a-license"
